### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by pedroprieto** [CintiaCastilloCareglio/FundamentosGit#1]
Buenas, @CintiaCastilloCareglio . Lo veo todo correcto. Un saludo!

**Comment by CintiaCastilloCareglio** [comment]
Buenas, @pedroprieto , ¿dejo este issue abierto para futuras correcciones o lo cerramos y ya haremos más? Gracias

**Comment by pedroprieto** [comment]
Puedes cerrarlo. Utilizaremos tu repositorio de trabajo mejor. Un saludo!
